//Prefix: SET, UPDATE, MAP, REMOVE,

//REGISTRATION ACTION TYPES:
export const MAP_REGISTRATION_FORM = "MAP_REGISTRATION_FORM";
export const UPDATE_REGISTER_STEP_STYLING = "UPDATE_REGISTER_STEP_STYLING";
export const UPDATE_REGISTRATION_FORM_DATA = "UPDATE_REGISTRATION_FORM_DATA,";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
