//Prefix: SET, UPDATE, MAP, REMOVE,

//REGISTRATION ACTION TYPES:
//1 Registration (Sign Up)
export const MAP_REGISTRATION_FORM = "MAP_REGISTRATION_FORM";
export const UPDATE_REGISTER_STEP_STYLING = "UPDATE_REGISTER_STEP_STYLING";
export const UPDATE_REGISTRATION_FORM = "UPDATE_REGISTRATION_FORM,";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const CHECK_DUPLICATION_SUCCESS = "CHECK_DUPLICATION_SUCCESS";
//2 Authentication (Sign In)
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
//3 Email verification
export const SET_EMAIL_VERIFICATION_CODE = "SET_EMAIL_VERIFICATION_CODE";
export const SET_EMAIL_VERIFICATION_STATUS = "SET_EMAIL_VERIFICATION_STATUS";

//COMMON UI: ALERT
export const SET_ALERT_NOTIFICATION = "SET_ALERT_NOTIFICATION";
export const REMOVE_ALERT_NOTIFICATION = "REMOVE_ALERT_NOTIFICATION";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const SET_DIALOG_BOX = "SET_DIALOG_BOX";
export const REMOVE_DIALOG_BOX = "REMOVE_DIALOG_BOX";

//MERCHANT-REGISTRATION ACTION TYPES:
export const GET_DETAIL_PROVIDER_INFO = "GET_DETAIL_PROVIDER_INFO";
export const UPDATE_MERCHANT_FORM_API = "UPDATE_MERCHANT_FORM_API";
export const UPDATE_MERCHANT_SUCCESS = "UPDATE_MERCHANT_SUCCESS";
export const UPDATE_MERCHANT_FAIL = "UPDATE_MERCHANT_FAIL";
