//Prefix: SET, UPDATE, MAP, REMOVE,

//REGISTRATION ACTION TYPES:
export const MAP_REGISTRATION_FORM = "MAP_REGISTRATION_FORM";
export const UPDATE_REGISTER_STEP_STYLING = "UPDATE_REGISTER_STEP_STYLING";
export const UPDATE_REGISTRATION_FORM = "UPDATE_REGISTRATION_FORM,";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const CHECK_DUPLICATION_SUCCESS = "CHECK_DUPLICATION_SUCCESS";

//COMMON UI: ALERT
export const SET_ALERT_NOTIFICATION = "SET_ALERT_NOTIFICATION";
export const REMOVE_ALERT_NOTIFICATION = "REMOVE_ALERT_NOTIFICATION";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//MERCHANT-REGISTRATION ACTION TYPES:
export const GET_DETAIL_PROVIDER_INFO = "GET_DETAIL_PROVIDER_INFO";
export const UPDATE_MERCHANT_FORM_API = "UPDATE_MERCHANT_FORM_API";
export const UPDATE_MERCHANT_SUCCESS = "UPDATE_MERCHANT_SUCCESS";
export const UPDATE_MERCHANT_FAIL = "UPDATE_MERCHANT_FAIL";
