export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

//REGISTRATION ACTION TYPES:
export const SET_REGISTER_STEP = "SET_REGISTER_STEP";
export const SET_USER_FORM_DATA = "SET_USER_FORM_DATA";
export const LOAD_REGISTER_FORM = "LOAD_REGISTER_FORM";
